---
os_timezone: Europe/Berlin
os_lang: 'en_US.UTF-8'
os_language: 'en_US:en'

common_tools:
  - curl
  - tar
  - unzip
  - git
  - tmux
  - the_silver_searcher
  - gnuplot
  - bash-completion
  - bash-completion-extras
  - htop
  - node_exporter
